### PR TITLE
Add support for importing tsv files

### PR DESCRIPTION
**Pull request by tamalign**
Hello team,

I've added support for importing TSV files in this pull request.

Please review the changes and let me know if there are any issues or further enhancements needed. If you are not accepting contributions at this moment, please inform me and I will close the PR.

Thank you!

### CODE REVIEW

**Comment by tbantle22** [comment]
Thank you for this contribution! I will review today

**Review by tbantle22 — APPROVED** [review]
Looks great! Will merge and get a release out shortly

**Comment by tbantle22** [comment]
This was released in 0.2.11

**Comment by tamalign** [comment]
@tbantle22 
Thank you for the review!

Would it be okay to create several more PRs (e.g., for bug fixes)? If it won't burden your team, I would love to contribute further.

**Comment by timsehn** [comment]
Pretty please! Keep em coming.

**Pull request merged**
